INSERT INTO Favourite (id,userid,moviesid) values (1,2,3)
INSERT INTO Favourite (id,userid,moviesid) values (2,1,1)
INSERT INTO Favourite (id,userid,moviesid) values (3,1,2)
INSERT INTO Movies (id, name, releasedyear, rating, genre, director,actor, duration,ownerid) values (1, 'The Office', '2020-10-10','5', 'Comedy','Mekdes','Jone Make', 120,1)
INSERT INTO Movies (id, name, releasedyear, rating, genre, director,actor, duration,ownerid) values (2, 'The Office 2', '2020-10-10','5', 'Comedy','Mekdes','Jone Make', 2,1)
INSERT INTO Movies (id, name, releasedyear, rating, genre, director,actor, duration,ownerid) values (3, 'The Office 3', '2020-10-10','5', 'Comedy','Mekdes','Jone Make', 2,1)
